### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by FGBxRamel** [ganeshh123/gta5-cleaner#10]
Hello there
Are contributions welcome?

**Comment by ganeshh123** [comment]
Sure!

**Comment by Michael21107** [comment]
time for a close lmao

**Comment by Michael21107** [comment]
@ganeshh123

**Comment by ganeshh123** [comment]
@Michael21107 sorry, closed.

**Comment by Michael21107** [comment]
> @Michael21107 sorry, closed.

no problem mate, just a reminder
