### ISSUE TITLE
title.rgl need to stay in dir folder to run now? Steam games

### ISSUE THREAD

**Issue by Crohnus1965** [ganeshh123/gta5-cleaner#12]
title.rgl need to stay in dir folder to run  now? Steam games 

https://github.com/ganeshh123/gta5-cleaner/assets/109772637/199f72ed-78c6-4a1a-96da-33bc73e604e9

**Comment by ganeshh123** [comment]
Thanks for letting me know.

I'll add that file in as well. In the meantime, please pull it out of the modstore folder yourself.

If you fancy you can add it yourself and open a PR :)

**Comment by Crohnus1965** [comment]
👍    I just happened to notice.   
  
Must be a new thing with the last update.   
  

  

  

  
  
  
  
>

**Comment by ganeshh123** [comment]
Thanks again for the report, it's been fixed in the latest versiom.

https://github.com/ganeshh123/gta5-cleaner/releases/tag/1.2.2
