### ISSUE TITLE
Auto-delete modstore

### ISSUE THREAD

**Issue by Michael21107** [ganeshh123/gta5-cleaner#13]
make `modstore` automatically delete when files are back in main folder

**Comment by Aidan-The-Dev** [comment]
Or.. Just take 2 seconds to delete the folder...?

**Comment by ganeshh123** [comment]
It should already do this, unless there's some files that couldn't be moved.

https://github.com/ganeshh123/gta5-cleaner/blob/71f756bbf6e2d4da6b9200e6d528197f9d93eb3f/app.js#L95C2-L95C47

**Comment by Michael21107** [comment]
looks like it does, thanks
