### ISSUE TITLE
Original ReadMe folder (Epic Games version tested) is also getting cleaned

### ISSUE THREAD

**Issue by Michael21107** [ganeshh123/gta5-cleaner#16]
![image](https://github.com/ganeshh123/gta5-cleaner/assets/121039033/0bbeb5da-d906-41d6-9fe2-9b06cd5f5402)

**Comment by ganeshh123** [comment]
Hey @Michael21107 , do you fancy fixing this and making a PR?

You just need to edit the `Readme` folder in `essentialFiles.js`, into `ReadMe` with a capital m.
https://github.com/ganeshh123/gta5-cleaner/blob/master/essentialFiles.js

If not, I can do it later on when I have some spare time.
