### ISSUE TITLE
Certain files won't move to modstore.

### ISSUE THREAD

**Issue by JRB921** [ganeshh123/gta5-cleaner#3]
![Screenshot 2021-12-23 220554](https://user-images.githubusercontent.com/96609475/147323199-55ebe6fc-2e65-4f2a-965e-b64803bf82b4.png)

**Comment by ganeshh123** [comment]
Hi, could you try [opening command prompt in your GTA 5 folder](https://youtu.be/IeFXb79nepc) and then typing:
`gta5cleaner.exe`
And then:
`clean`
And post a screenshot or output of what it says?

**Comment by ganeshh123** [comment]
Duplicate of #1
