### ISSUE TITLE
Where does the files go?

### ISSUE THREAD

**Issue by itsmeares** [ganeshh123/gta5-cleaner#6]
Hi, I just want to ask where does the files go because I want to delete the mods and the cleaner at the same moment is this possible? Like when I clear the mods than I delete the cleaner will it work or store the mods in a folder or something like that?

**Comment by ganeshh123** [comment]
Hi, they get stored in the "modstore" folder created in your GTA 5 install folder.

You can simply delete "gta5cleaner.exe" and your "modstore" folder.

**Comment by itsmeares** [comment]
Thank you for the answer!

**Comment by Michael21107** [comment]
@ganeshh123 pls close
